name: Android Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Download Dependencies
        run: ./gradlew androidDependencies

      - name: Run Build
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew lint test

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/test-results

      - name: Save Build Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            app/build/reports
            app/build/outputs/apk/debug/
